### PR TITLE
Reorder init to match MP startup

### LINKED ISSUE #897: LucasArts intro video has distorted audio
**Operating system and version:**
(Arch) Linux 64-bit, OpenJK (JK2) built from Git master on 19 November.

**Is this for single player or multiplayer?**
Single player.

**Description of the bug (and if possible, steps to reproduce the bug):**
The JK2 SP intro video with the LucasArts logo exhibits slightly distorted audio. I can still make out the sound but it seems to skip audio in intervals of about ~75 ms.

I'm using PulseAudio, not sure if it's related. If there is any other information you need that may be useful in debugging such an issue, I'd be happy to provide it. It may be worth mentioning that the LucasArts intro video in JA _does_ sound fluent and is not distorted.

It's not really a major issue or one that bothers me in particular, but I thought I'd report it anyway.

**What did you expect to happen instead?**
The sound to play fluently.

### PR DESCRIPTION
**Pull request by TwelveEyes**
Reorders SP startup init calls to match the order of the MP binary. Fixes the audio distortion during the LucasArts intro video.

Fixes #897

### CODE REVIEW

File: code/qcommon/common.cpp [hunk 1]
```diff
@@ -1196,6 +1196,7 @@ void Com_Init( char *commandLine ) {
 				Cbuf_AddText ("cinematic openinglogos\n");
 			}
 		}
+		CL_StartHunkUsers();
```
Comment (TwelveEyes) [inline code/qcommon/common.cpp:1199]: I'm unsure this call is necessary. I only added it so SP and MP match 1:1.

Comment (ensiform) [reply code/qcommon/common.cpp:1199]: That is the only part of what makes the fix happen, the moving of the other two functions has no effect on the sound code.

**Comment by ensiform** [comment]
In a perfect world, would just remove SP engine and make SP features work in "MP" sans a real server connectivity.
